website/models.py
from . import db

class Stock(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    symbol = db.Column(db.String(6), unique=True)
    price = db.Column(db.Numeric(10,2), nullable=True)
    open = db.Column(db.Numeric(10,2), nullable=True)
    close = db.Column(db.Numeric(10,2), nullable=True)
    mcap = db.Column(db.Numeric(10,2), nullable=True)
    volume = db.Column(db.Numeric(10,2), nullable=True)
    dmin = db.Column(db.Numeric(10,2), nullable=True)
    dmax = db.Column(db.Numeric(10,2), nullable=True)
    ymin = db.Column(db.Numeric(10,2), nullable=True)
    ymax = db.Column(db.Numeric(10,2), nullable=True)

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_security import Security
from os import path

db = SQLAlchemy()
DB_NAME = "metricshare.db"

def create_db(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print("The database has been created.")


def create_app():
    app = Flask(__name__)
    #TODO: Secure cookies and session data - Remove in production!!
    app.config['SECRET_KEY'] = 'ThisIsMyKey'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False # For the warning
    db.init_app(app)

    from .views import views

    app.register_blueprint(views,url_prefix='/')

    from .models import Stock

    create_db(app)

    return app

website/views.py
'''
Application blueprint, it stores all the paths to the pages the user will be able to navigate to.
'''
from flask import Blueprint, render_template, request, flash, json, send_file, abort
from flask_sqlalchemy import SQLAlchemy
from .models import Stock
import pandas as pd
from fin_scraper import FinScraper
from rss_scraper import NewsScraper
import requests, io, base64, datetime
import matplotlib.pyplot as plt
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
import yfinance as yf
import os

views = Blueprint('views', __name__)
db = SQLAlchemy()
path = "C:\\Users\\dorac\\OneDrive\\Desktop\\Anul 3\\Web Technologies\\Scraper"

def filter(user_input):
    '''
    :param user_input: can be in the form of a string 'SYMBOL' or 'SYMB1, SYMB2, SYMB3, ...'
    :return: list if it is comma separated, otherwise the same
    '''
    if user_input.find(',')==-1:
        print(user_input)
        return user_input
    else:
        symbols = [x.strip() for x in user_input.split(',')]
        return symbols

def scraper_lst(tickers):
    '''
    :return: Nested list with market data for multiple stocks
    '''
    stocks = []
    for ticker in tickers:
        scr = FinScraper(ticker)
        stock_values = scr.scraper()
        stocks.append(stock_values)
        del scr
    return stocks

def plot_multiple(tickers):
    '''
    Plots multiple stocks for today.
    :param tickers: a list of all stock symbols to plot
    :return:
    '''
    fig = plt.figure(figsize=(16, 8))
    for symb in tickers:
        stock = yf.Ticker(symb[0])
        stock_dict = stock.history(period='5y', interval='1mo')
        plt.plot(stock_dict['Close'].bfill(), label=f'{symb}')
    plt.title(f"Market Prices Comparison - 5 Years", fontsize=20)
    plt.xlabel('Time')
    plt.ylabel('Price')
    plt.grid()
    plt.legend()
    # Plot to png
    pngImage = io.BytesIO()
    FigureCanvas(fig).print_png(pngImage)
    # Encode img to base64 string
    png = "data:image/png;base64,"
    png += base64.b64encode(pngImage.getvalue()).decode('utf8')

    return png

def plot_price_day(ticker, stock):
    '''
    :param ticker: for format use
    :param stock: the yahoo finance stock object
    :return: Timeseries of today's market prices for a stock
    '''
    stock_dict = stock.history(period='1d',interval='1m')
    #print(stock_dict['Close'].head())

    fig = plt.figure(figsize=(16, 8))
    plt.plot(stock_dict['Close'], label='Close Price history', color="green")
    plt.title(f"{ticker.upper()} Market Prices - Date : {datetime.date.today()}",fontsize=20)
    plt.xlabel('Time')
    plt.ylabel('Price')
    plt.grid()
    # plt.savefig(f'/static/images/{ticker}_{datetime.date.today()}_prices.png')
    # Plot to png
    pngImage = io.BytesIO()
    FigureCanvas(fig).print_png(pngImage)
    # Encode img to base64 string
    png = "data:image/png;base64,"
    png+= base64.b64encode(pngImage.getvalue()).decode('utf8')

    return png


@views.route('/',methods=['GET','POST'])
def home():
    data = request.form.get('user-query')
    result = None
    image = None
    multiple = True
    yaxis = []
    if data:
        filtered = filter(data)
        if isinstance(filtered, list):
            try:
                multiple = True
                result = scraper_lst(filtered)
                print('--- (TIME SERIES) : Plot has been generated ---\n')
                image = plot_multiple(filtered)
                flash("Success! See below for results.", category='success')
            except:
                flash("Invalid input, please try again. The input should either be one stock ticker/name or multiple (separate them by commas).(e.g: APPL,SBUX,MSFT)", category='error')
        else:
            try:
                multiple = False
                fs = FinScraper(filtered)
                result = fs.scraper()
                print("--- (FIN SCRAPER) : Input has been scraped and result displayed ---\n",result)
                stock = yf.Ticker(result[0])
                # stock_dict = stock.history(period='1d', interval='1m')
                # yaxis = stock_dict['Close'].bfill().tolist()
                image = plot_price_day(filtered, stock)
                print("--- (TIME SERIES) : Plot has been generated ---\n")
                #history = fs.hist_data(result[0])
                history = stock.history(period='1d',interval='1m')
                print(data)
                history.to_csv(os.path.join(path, r'hist.csv'), index = None, header=True)
                print("--- (HISTORICAL DATA) : History saved to csv and sent to HTML ---\n")
                flash("Success! See below for results.", category='success')
            except:
                flash("Invalid input, please try again. The input should either be one stock ticker/name or multiple (separate them by commas).(e.g: APPL,SBUX,MSFT)", category='error')

    return render_template("home.html",result = result,img = image,multiple=multiple, yaxis=yaxis)

@views.route("/download")
def download_file():
    return send_file(
        os.path.join(path, r'hist.csv'),
        mimetype='text/csv',
        attachment_filename='hist.csv',
        as_attachment=True)


@views.route('/about')
def about():
    return render_template("about.html")

@views.route('/feed')
def feed():
    ns = NewsScraper('ticker')
    print('--- RSS SCRAPER : Jsonifying scraped results ---')
    articles = ns.scraper()
    print(articles)
    ns.save_to_json(articles)
    data = json.load(open('./articles.json'))
    return render_template('feed.html', data=data)

website/templates/about.html
{% extends "base.html" %}

{% block content %}

<section class="bg-dark text-light p-5 p-lg-0 pt-lg-5 text-justify text-sm-start">
    <div class="container">
         <h1 class="text-center">
             <span>Quick Guide</span>
        </h1>
        <p>
            On the main page, the search field awaits user input of no more than 200 characters. You can therefore
        opt either for trends on a specific stock or for multiple. For one stock, the name or ticker of the stock
        should be inserted in the field. For more than one stocks, a list separated by commas can be written
        into the field. The input will not be recognized if it is anything else but a stock name/ticker or multiple stock/tickers separated by commas.
        </p>
        <p>
            Once the search parameters have been set, by clicking the ”Enter” button, the page will display the queried data.
        Either a table (or formatted data) has been displayed, along with plot.
        The requested information can be available to download as CSV by pressing the ”Download” button
        Data displayed will include day range, close and open price, volume and other specifics.
        The feed tab, displays news relevant to trend stocks.
        </p>
        <p>
            The main service featured by the application is the scraper tool which gathers data from other
        web services in order to then get structured data to the client on his queried stocks. There are two
        scrapers which have different properties. One which will get news from an RSS Feed on SeekingAlpha,
        and another which collects a batch of stock market data from Yahoo Finance and Google Finance. The batch
        will include stocks from chosen dates and will query specific stock tickers.
        </p>
        <p>
            The plots will depend on queried data. If the someone queries multiple stocks, the plot will show a comparison
        between prices in the last 5 years, each line marked by different colors. If someone queries only one stock, the plot
        the plot will be relevant for that day's prices in a time series.
        </p>
        <p>
            This web application displays and gathers information
        on the Stock Market with the use of scraper tools. News about stock trends, as well as numerical
        data, is parsed and display according to a predefined standard. Because stock investments can
        put personal capital at risk, the application’s goal is to inform users of its dangers and benefits.
        However, none of the collected data should serve as financial advice, and users should reach their
        own conclusions when faced with factual data or public opinions.
        </p>
        <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec suscipit ligula felis, ut maximus purus aliquam at. Fusce at dolor id velit porta ultrices sit amet a urna. Mauris id neque sapien. Nullam vel molestie nisl, in tincidunt risus. Vivamus sed lorem felis. Quisque pretium arcu et faucibus eleifend. Cras non justo viverra, venenatis enim et, laoreet nisl. Nulla facilisi. Phasellus ante magna, condimentum vel tempus vel, mattis vitae ipsum. Etiam nisl ante, fringilla et efficitur a, luctus vel nunc. Integer aliquam purus vitae turpis varius posuere.

Mauris viverra sem quis tempor egestas. Integer posuere vel velit id tristique. Curabitur laoreet vehicula tortor at lobortis. Donec a lectus ac justo molestie interdum a eu odio. Quisque sit amet dui non lorem lobortis pretium aliquet at augue. In ut sollicitudin mauris. In nec nunc eros. Curabitur vel semper purus. Donec vehicula convallis nulla, nec ultrices turpis dignissim ut. Nam ornare risus et velit pulvinar, sit amet pretium neque eleifend. </p>
    </div>

</section>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}MetricShare - Stocks Data{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          crossorigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
        />

        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='/style/home.css') }}">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js"></script>

    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3">
            <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbar"
            >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-header">
              <a class="navbar-brand" href="#">MetricShare</a>
            </div>
            <div class="collapse navbar-collapse" id="navbar">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" id="home" href="/">Home</a>
                    <a class="nav-item nav-link" id="about" href="/about">About</a>
                    <a class="nav-item nav-link" id="feed" href="/feed">Feed</a>
                </div>
            </div>
        </nav>

        {% block content %} {% endblock %}

        <script
            src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"
        ></script>
        <!-- Footer -->
        <footer class="bg-dark text-center text-white">
            <!-- Copyright -->
            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">© 2021 Copyright:
                <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap</a>,
                <a class="text-white" href="https://www.google.com/finance/">GoogleFinance</a>,
                <a class="text-white" href="https://finance.yahoo.com/">YahooFinance</a>,
                <a class="text-white" href="https://seekingalpha.com/">SeekingAlpha</a>,
                <a class="text-white" href="https://github.com/CaleaD">Github.com/CaleaD</a>
            </div>
        </footer>
        <!--<script
          type="text/javascript"
          src="{{ url_for('static', filename='index.js') }}"
        ></script>-->
    </body>
</html>

website/templates/display.html
<html>
  <head>
    <!--Forecord, MetricShare, DataWizard, StakeMetrics-->
    <title>MetricShare - Display Data</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='/style/display.css') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body>
    <div class="container">
      <div class="navbar">
        <!--<img src="assets/logo.png" alt="logo" />-->
        <h1>MetricShare</h1>
        <ul>
          <li><a href="../home.html">Home</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
      </div>
    </div>
    <div class="main">
      <div class="left-column">
        <img src="{{ url_for('static', filename='/assets/graph_placeholder.png') }}" alt="stocks-image" />
      </div>
      <div class="right-column">
        <h1>Stock Data &bullet; <span>[Ticker/Name]</span></h1>
        <h2>
          Market Status: <span> [Closed/Open] </span>(will open tomorrow at
          [hour])
          <br />
          Close/Current Price: <span>$[Amount]</span><br />
          Max Price: <span>$[Amount]</span><br />
          Min Price: <span>$[Amount]</span><br />
          Volume: <span>[Amount]</span>
        </h2>
        <div class="buttons">
          <ul>
            <li><button type="submit">Download</button></li>
            <li>
              <form action="../home.html">
                <button type="submit">Search Again</button>
              </form>
            </li>
          </ul>
        </div>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi dicta
          saepe dolorem cum maxime tenetur accusamus, veniam nesciunt eius vero
          accusantium aut, fuga quibusdam autem molestias voluptas. A, suscipit
          inventore!
        </p>
      </div>
    </div>
    <div class="news">
      <h1>News Feed for <span>[Ticker/Name]</span></h1>
      <!-- Just for design, replace with real RSS later-->
      <ul>
        <li id="alt">
          <a href="#"
            ><h2>
              Longeveron stock rockets on very heavy volume after upbeat FDA
              news
            </h2></a
          >
          <p>
            Shares of Longeveron Inc. blasted 120.9% higher on very active
            morning trading Thursday, after the biotechnology company said its
            Lomecel-B for the treatment of a congenital heart defect in infants
            (Hypoplastic Left Heart Syndrome) affecting about 1,000 babies a
            year was granted rare pediatric disease (RPD) designation by the
            Food and Drug Administration. Trading volume exploded to 112.0
            million shares, compared with the full-day average of about 110,000
            shares. The stock was both the biggest gainer and most active on
            major U.S. exchanges. The company said Lomecel-B is currently being
            evaluated in a Phase 2 trial. Despite the rally, the…
          </p>
        </li>
        <li>
          <a href="#"
            ><h2>
              EIA reports a 26-billion-cubic-foot weekly climb in natural-gas
              supplies
            </h2></a
          >
          <p>
            The U.S. Energy Information Administration reported on Thursday that
            domestic supplies of natural gas rose by 26 billion cubic feet for
            the week ended Nov. 12. IHS Markit had forecast an increase of 24
            billion cubic feet. Total stocks now stand at 3.644 trillion cubic
            feet, down 310 billion cubic feet from a year ago and 81 billion
            cubic feet below the five-year average, the government said.
            Following the data, December natural gas traded up by 13.4 cents, or
            2.8%, at $4.95 per million British thermal units. Prices were at
            $4.961 shortly before the data. Market Pulse Stories are Rapid-fire…
          </p>
        </li>
        <li id="alt">
          <a href="#"
            ><h2>
              Cisco's stock set to suffer biggest selloff in 15 months, shaves
              points off the Dow's price
            </h2></a
          >
          <p>
            Shares of Cisco Systems Inc. tumbled 9.0% in toward a six-month low
            in morning trading Thursday, to pace both the Dow Jones Industrial
            Average's and S&P 500's decliners, in the wake of the networking
            company's disappointing fiscal first-quarter report. The stock is
            headed for the biggest one-day percentage selloff since it plunged
            11.2% on Aug. 13, 2020, which followed Cisco's fiscal fourth-quarter
            2020 results. The stock's price decline of $5.09 was shaving about
            34 points off the Dow's price, which is down 188 points, or 0.5%. If
            there is a silver lining to Cisco's stock drop, it's that Cisco's
            stock…
          </p>
        </li>
        <li>
          <a href="#"
            ><h2>
              Leading indicators point to acceleration in U.S. economy
            </h2></a
          >
          <p>
            The U.S. leading economic index jumped 0.9% in October and pointed
            toward a pickup in growth toward the end of 2021, the Conference
            Board said Thursday. "The U.S. LEI rose sharply in October
            suggesting the current economic expansion will continue into 2022
            and may even gain some momentum in the final months of this year,"
            said Ataman Ozyildirim, director of business cycles research at the
            board. The one caveat: Rising Covid cases in parts of the Northeast
            and Midwest. That could mar an otherwise strong finish to the year.
            The leading index had increased just 0.1% in September and 0.7%…
          </p>
        </li>
        <li id="alt">
          <a href="#"
            ><h2>
              Ford's credit rating outlook swings to positive at S&P, putting it
              in line for a bump up to investment grade
            </h2></a
          >
          <p>
            The U.S. leading economic index jumped 0.9% in October and pointed
            toward a pickup in growth toward the end of 2021, the Conference
            Board said Thursday. "The U.S. LEI rose sharply in October
            suggesting the current economic expansion will continue into 2022
            and may even gain some momentum in the final months of this year,"
            said Ataman Ozyildirim, director of business cycles research at the
            board. The one caveat: Rising Covid cases in parts of the Northeast
            and Midwest. That could mar an otherwise strong finish to the year.
            The leading index had increased just 0.1% in September and 0.7%…
          </p>
        </li>
      </ul>
      <!--<script src="//rss.bloople.net/?url=http%3A%2F%2Ffeeds.marketwatch.com%2Fmarketwatch%2Fmarketpulse%2F&detail=100&limit=5&showtitle=false&type=js"></script>-->
    </div>
  </body>
</html>

website/templates/home.html
{% extends "base.html" %}

{% block content %}
    <section class="text-light p-5 p-lg-0 pt-lg-5 text-center text-sm-start" style="background-image: url('../static/assets/stocks3.jpeg')">
        <div class="container">
            <!-- Handling Error Messages -->
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category,msg in messages %}
                    {% if category == 'error' %}
                        <div class="alert alert-danger alter-dismissible fade show" role = "alert">
                            {{ msg }}
                            <button type="button" class="close" data-dismiss="alert">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% else %}
                        <div class="alert alert-success alter-dismissible fade show" role = "alert">
                            {{ msg }}
                            <button type="button" class="close" data-dismiss="alert">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
            {% endwith %}
            <div class="d-sm-flex align-items-center justify-content-between" style="background-color: rgba(0, 0, 0, 0.5);">
                <div class="left-column">
                    <h1>Stock <span>Market </span>Overview</h1>
                    <h3>
                        Search market data and analyse the performance of your<span> shares </span>and<span>
                    investments </span>with the click of a button.
                    </h3>
                <form method="POST">
                    <div class="search-bar">
                        <input
                        type="search"
                        placeholder="Search"
                        id="site-search"
                        name="user-query"
                        aria-label="Search through site content"
                        maxlength="200"
                        />
                        <!--For design example, redirect to display page. Modify action later-->
                        <button class="col-xs-12" type="submit">
                            Enter
                        </button>
                    </div>
                </form>
                    <p>
                        This site does not serve as a financial advice platform. It provides factual data and news articles which may or may not be objective, but that belongs to the author in question. </p>
                </div>
                <div class="right-column">
                    <img src="{{ url_for('static', filename='/assets/scraping.png') }}" alt="stocks-image" class="img-responsive1"/>
                </div>
            </div>
        </div>
    </section>

    {% if result != None %}
        {% if multiple == False %}
            <section class="bg-dark text-light p-5 p-lg-0 pt-lg-5 text-center align-items-center text-sm-start">
                <div class="d-sm-flex align-items-center justify-content-between">
                        <div class="left-column">
                            <img class="img-fluid rounded img-responsive1" src={{img}} alt="{{img}}"/>
<!--                            <canvas id="myChart" width="600" height="400"></canvas>-->
<!--                            <script>-->
<!--                                var ctx = document.getElementById("myChart").getContext("2d");-->
<!--                                var chart = new Chart(ctx, {-->
<!--                                  type: "line",-->
<!--                                  data: {-->
<!--                                    labels: ['00:00','01:15', '02:00', '03:20', '04:00', '05:00',-->
<!--                                        '06:00','07:00','08:00','09:00','10:00','11:00','12:00',-->
<!--                                        '13:00','14:00','15:00','16:00','17:00','18:00','23:59'],-->
<!--                                    datasets: [-->
<!--                                      {-->
<!--                                        label: "{{result[7]}} Prices Today",-->
<!--                                        backgroundColor: "rgb(50, 199, 65)",-->
<!--                                        borderColor: "rgba(99, 255, 132,1)",-->
<!--                                        data: {{yaxis | safe}},-->
<!--                                      }-->
<!--                                    ]-->
<!--                                  },-->
<!--                                  options: {-->
<!--                                    responsive:false,-->
<!--                                    maintainAspectRatio: false-->
<!--                                  }-->
<!--                                });-->
<!--                            </script>-->
                        </div>
                    <div class="right-column">
                        <h1>Stock Data &bullet; <span>{{result[7]}} ({{result[0]}})</span></h1>
                        <h2>
                            Market Status: <span> {{result[1]}} </span>
                            <br />
                            Current Price: <span>${{result[2]}}</span><br />
                            Open Price: <span>${{result[3]}}</span><br />
                            Close Price: <span>${{result[4]}}</span><br />
                            Market Cap: <span>${{result[5]}}</span><br />
                            Volume: <span>${{result[6]}}</span><br />
                            Day Range: <span>${{result[8]}} - ${{result[9]}}</span><br />
                            {% if result|length == 12%}
                            Year Range: <span>${{result[10]}} - ${{result[11]}}</span><br />
                            {% endif %}
                        </h2>
                    </div>
                </div>
                <div class="p-2">
                    <form method="GET" action="{{url_for('views.download_file')}}">
                        <button type="submit">Download CSV</button>
                    </form>
                </div>
            </section>
        {% else %}
            <section class="bg-dark p-5 p-lg-0 pt-lg-5 text-center align-items-center text-sm-start">
                    <div class="main">
                        <table class="center">
                            <thead>
                                <tr>
                                    <th>Stock Name</th>
                                    <th>Ticker</th>
                                    <th>Current Price</th>
                                    <th>Open Price</th>
                                    <th>Close Price</th>
                                    <th>High</th>
                                    <th>Low</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for stock in result %}
                                <tr>
                                    <td>{{stock[7]}}</td>
                                    <td>{{stock[0]}}</td>
                                    <td>${{stock[2]}}</td>
                                    <td>${{stock[3]}}</td>
                                    <td>${{stock[4]}}</td>
                                    <td>${{stock[9]}}</td>
                                    <td>${{stock[8]}}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>>
                    </div>
                    {% if img != None %}
                        <div class="mx-auto p-5">
                            <img class="img-fluid rounded img-responsive1 w-50 h-50" src={{img}} alt="{{img}}"/>
                        </div>
                    {% endif %}
<!--                    <div class="p-2">-->
<!--                        <button type="submit">Download CSV</button>-->
<!--                    </div>-->
            </section>
        {% endif %}
    {% endif %}

    <!-- Boxes -->
    <section class="bg-secondary text-light p-1 p-lg-0 pt-lg-5 text-center text-sm-start">
        <div class="container">
            <div class="row text-center">
                <div class="col-md d-flex align-items-stretch">
                    <div class="card bg-dark text-light">
                        <div class="card-body text-center">
                            <h1 mb-3>
                                <i class="bi bi-bar-chart-line"></i>
                            </h1>
                            <h3 class="card-title mb-3">Graphs</h3>
                            <p class="card-text">
                                Be in tune with financial trends by following stock market prices aided by visual graphs.
                            </p>
                        </div>
                    </div>

                </div>
                <div class="col-md d-flex align-items-stretch">
                    <div class="card bg-dark text-light">
                        <div class="card-body text-center">
                            <h1 mb-3>
                                <i class="bi bi-newspaper"></i>
                            </h1>
                            <h3 class="card-title mb-3">News</h3>
                            <p class="card-text">
                                Read the newsfeed and stay on top of your favorite stocks.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md d-flex align-items-stretch">
                    <div class="card bg-dark text-light">
                        <div class="card-body text-center">
                            <h1 mb-3>
                                <i class="bi bi-download"></i>
                            </h1>
                            <h3 class="card-title mb-3">Data</h3>
                            <p class="card-text">
                                Download the data we scraped for you and share it with others.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}